[project]
name = "temp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "imdbpy>=2022.7.9",
    "playwright>=1.53.0",
    "pyfzf>=0.3.1",
    "requests>=2.32.4",
]
